"""item table

Revision ID: c474fa5ac54b
Revises: 
Create Date: 2022-02-21 13:00:02.371058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c474fa5ac54b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('country_name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_country_name'), 'item', ['country_name'], unique=False)
    op.create_index(op.f('ix_item_identifier'), 'item', ['identifier'], unique=False)
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=False)
    op.create_index(op.f('ix_item_price'), 'item', ['price'], unique=False)
    op.create_index(op.f('ix_item_timestamp'), 'item', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_timestamp'), table_name='item')
    op.drop_index(op.f('ix_item_price'), table_name='item')
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_identifier'), table_name='item')
    op.drop_index(op.f('ix_item_country_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
